# Limit Operator (LIMIT offset_value, limit_value)

# The limit has a value of 10 if not specified. However, if it's specified, the value must be between 0 and 10.000.

query GeolocCountryNameLimit50{
  httpMetrics(
    offset: 0
    limit: 50  # In this example, we'll retrieve data from row 0 to row 50.
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
  ) 
  {        
    ts
    host
    geolocCountryName
  }
}
