# Offset Operator (LIMIT offset_value, limit_value)

# The offset has a value of 0 if not specified. The maximum value for the offset isn't restricted,
# but it works in conjunction with the limit operator, which restricts the number of rows returned.

query GeolocCountryNameOffset100{
  httpMetrics(
    offset: 100  # In this example, we'll retrieve data starting from row 100 up to row 150 (limit).
    limit: 50
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
    }
  ) 
  {        
    ts
    host
    geolocCountryName
  }
}
