query EventsTopIPCountryCGNAT {
 httpEvents(
   limit: 10
   filter: {
     tsRange: {begin:"2023-03-25T08:36:10", end:"2023-03-27T11:36:10"}
   }
   aggregate: {count: remoteAddress}
   groupBy: [remoteAddress, geolocAsn, geolocCountryName, source]
   orderBy: [count_DESC]
   )
 {
   remoteAddress
   geolocAsn
   geolocCountryName
   source
   count
 }
}
