query IdnsTotalQueries {
  idnsQueriesMetrics(
    limit: 1000, 
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    aggregate: {
        sum: requests
    }
    groupBy: [ts]
    orderBy: [ts_ASC]
    ) 
  { 
    ts
    sum
  }
}
