query AverageRequestTimeByHostAndLocation {
  httpEvents(
    limit: 100
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
    }
    aggregate: {avg: requestTime} 
    groupBy: [host, geolocCountryName, geolocRegionName]
    orderBy: [avg_DESC]
  )
  {
    host
    geolocCountryName
    geolocRegionName
    avg
  }
}


## Example response

{
  "data": {
    "httpEvents": [
      {
        "host": "adomain.net",
        "geolocCountryName": "United States",
        "geolocRegionName": "Oregon",
        "avg": 374.572
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Santa Catarina",
        "avg": 224.33
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Santa Catarina",
        "avg": 222.908
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Santa Catarina",
        "avg": 195.766
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "avg": 189.937
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 181.029
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 180.96
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 180.956
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Santa Catarina",
        "avg": 180.953
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 180.94
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Santa Catarina",
        "avg": 180.937
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 180.925
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 180.849
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Parana",
        "avg": 180.827
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 180.769
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Bahia",
        "avg": 180.006
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 180.003
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio de Janeiro",
        "avg": 180.001
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 180
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Santa Catarina",
        "avg": 176.848
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio de Janeiro",
        "avg": 176.657
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 174.453
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "avg": 167.108
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 163.743
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 162.831
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 160.803
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 160.405
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sergipe",
        "avg": 159.495
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Piaui",
        "avg": 159.428
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio de Janeiro",
        "avg": 159.209
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 158.68
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 157.007
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio de Janeiro",
        "avg": 156.286
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 156.058
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Bahia",
        "avg": 156.043
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 155.768
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 154.497
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 153.118
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "avg": 152.882
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 152.395
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 151.79
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 150.887
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Pernambuco",
        "avg": 150.75
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 150.563
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 150.284
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "avg": 150.248
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Piaui",
        "avg": 149.857
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Parana",
        "avg": 149.509
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Goias",
        "avg": 148.66
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 148.438
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 148.403
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 148.381
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 147.807
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 147.624
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Piaui",
        "avg": 146.998
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Pernambuco",
        "avg": 146.855
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 146.808
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 146.601
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Parana",
        "avg": 146.523
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 146.375
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 145.627
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Goias",
        "avg": 145.532
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 145.005
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 144.82
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "avg": 144.772
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "avg": 144.619
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "avg": 144.395
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 144.351
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 144.281
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 144.236
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 144.205
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio de Janeiro",
        "avg": 144.118
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Espirito Santo",
        "avg": 143.78
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Maranhao",
        "avg": 143.23
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 143.097
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "avg": 142.62
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 142.434
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 142.344
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Para",
        "avg": 141.162
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 141.069
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "avg": 140.967
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Bahia",
        "avg": 140.196
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Norte",
        "avg": 139.991
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 139.978
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Pernambuco",
        "avg": 139.912
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Santa Catarina",
        "avg": 139.284
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Parana",
        "avg": 139.161
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 138.697
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "avg": 138.668
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 138.408
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 138.34
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Mato Grosso",
        "avg": 137.108
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "avg": 137.038
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 137.021
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 136.942
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 136.737
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "avg": 136.612
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Roraima",
        "avg": 136.494
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Mato Grosso",
        "avg": 136.399
      },
      {
        "host": "adomain.net",
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "avg": 136.364
      }
    ]
  }
}
