query HttpCalculatedDataTransferred {
  httpMetrics(
    limit: 2000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    groupBy:[ts]
    orderBy:[ts_ASC]
  )
  {
    ts
    dataTransferredIn
    dataTransferredOut
    dataTransferredTotal
  }
}
