query HttpCalculatedRequests2xxStatusCode {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
    }
    groupBy: [ts]
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    requestsStatusCode2xx
    requestsStatusCode200
    requestsStatusCode204
    requestsStatusCode206
  }
}
