query HttpCalculatedRequests4xxStatusCode {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
    }
    groupBy: [ts]
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    requestsStatusCode4xx
    requestsStatusCode400
    requestsStatusCode403
    requestsStatusCode404
  }
}
