query HttpCalculatedRequests5xxStatusCode {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    groupBy: [ts]
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    requestsStatusCode5xx
    requestsStatusCode500
    requestsStatusCode502
    requestsStatusCode503
  }
}
