query HttpCalculatedWAFXssAttacks {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"2022-06-20T12:59:00" end:"2022-06-22T14:15:00"}
    }
    groupBy: [ts]
    orderBy: [ts_ASC]
  ) 
  { 
    ts,
    wafRequestsXssAttacks
  }
}
