query BandwidthAndBlockedRequestsLocation {
  httpMetrics(
    limit: 5
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
      # blockeds
      wafLearningEq: "0"
      wafBlockEq: "1"
    }
    aggregate: {count: rows} 
    groupBy: [geolocCountryName, geolocRegionName]
    orderBy: [count_DESC]
  )
  {
    geolocCountryName
    geolocRegionName
    bandwidthTotal
    count
  }
}


## Example response

{
  "data": {
    "httpMetrics": [
      {
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Sao Paulo",
        "bandwidthTotal": 168502607.7333336,
        "count": 17067
      },
      {
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Minas Gerais",
        "bandwidthTotal": 55766709.99999997,
        "count": 6623
      },
      {
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio de Janeiro",
        "bandwidthTotal": 63319467.466666654,
        "count": 5166
      },
      {
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Rio Grande do Sul",
        "bandwidthTotal": 45501784.66666666,
        "count": 4698
      },
      {
        "geolocCountryName": "Brazil",
        "geolocRegionName": "Bahia",
        "bandwidthTotal": 27374068.533333324,
        "count": 3999
      }
    ]
  }
}
