query RequestsBlockedXTotalByHost {
  httpMetrics(
    limit: 5
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    groupBy: [host]
    orderBy: [wafRequestsBlocked_DESC]
  )
  {
    host
    wafRequestsBlocked
    edgeRequestsTotal
  }
}


## Example response

{
  "data": {
    "httpMetrics": [
      {
        "host": "adomain.net",
        "wafRequestsBlocked": 0,
        "edgeRequestsTotal": 1
      },
      {
        "host": "adomain.net",
        "wafRequestsBlocked": 0,
        "edgeRequestsTotal": 1
      },
      {
        "host": "adomain.net",
        "wafRequestsBlocked": 0,
        "edgeRequestsTotal": 1
      },
      {
        "host": "adomain.net",
        "wafRequestsBlocked": 0,
        "edgeRequestsTotal": 1
      },
      {
        "host": "adomain.net",
        "wafRequestsBlocked": 0,
        "edgeRequestsTotal": 1
      }
    ]
  }
}
