query TotalAttacksWAFAndTotalBytesSentByHost {
  httpMetrics(
    limit: 5
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    aggregate: {sum: bytesSent},
    groupBy: [host]
    orderBy: [wafRequestsThreat_DESC]
  )
  {
    host
    wafRequestsThreat
    bytes: sum
  }
}

## Example response

{
  "data": {
    "httpMetrics": [
      {
        "host": "adomain.com",
        "wafRequestsThreat": 9093896,
        "bytes": 118562658876
      },
      {
        "host": "adomain.com",
        "wafRequestsThreat": 7676210,
        "bytes": 27744691371
      },
      {
        "host": "adomain.com",
        "wafRequestsThreat": 754767,
        "bytes": 161574459469
      },
      {
        "host": "adomain.com",
        "wafRequestsThreat": 383461,
        "bytes": 3628591934
      },
      {
        "host": "adomain.com",
        "wafRequestsThreat": 374418,
        "bytes": 3196861431
      }
    ]
  }
}
