query DataStreamedLines {
  dataStreamedMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    aggregate: {
      sum: streamedLines
    }
    groupBy: [ts]
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    sum
  }
}
