query HttpCalculatedWARfiAttack {
  httpMetrics(
    limit: 100
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    groupBy: [ts]
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    wafRequestsRfiAttacks
  }
}
