query DataStreamedLines {
  dataStreamedMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
    }
    aggregate: {
      sum: streamedLines
    }
    groupBy: [ts]
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    sum
  }
}
