# Count Function - COUNT(*) or COUNT(field)

query CountRowsByHost {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
    }
    aggregate: {count:rows}  # {count:host}
    groupBy: [host]
    orderBy: [count_DESC]
  ) 
  {        
    host
    count
  }
}
