# Count Function - COUNT(*) or COUNT(field)

query CountRowsByHost {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    aggregate: {count:rows}  # {count:host}
    groupBy: [host]
    orderBy: [count_DESC]
  ) 
  {        
    host
    count
  }
}
