# Maximum Function - MAX(field)

query MaxRequestTimeByHost {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    aggregate: {max: requestTime}
    groupBy: [host]
    orderBy: [max_DESC]
  ) 
  {        
    host
    max
  }
}
