# Maximum Function - MAX(field)

query MaxRequestTimeByHost {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
    }
    aggregate: {max: requestTime}
    groupBy: [host]
    orderBy: [max_DESC]
  ) 
  {        
    host
    max
  }
}
