# Minimum Function - MIN(field)

query MinRequestTimeByHost {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    aggregate: {min: requestTime}
    groupBy: [host]
    orderBy: [min_DESC]
  ) 
  {        
    host
    min
  }
}
