# Minimum Function - MIN(field)

query MinRequestTimeByHost {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
    }
    aggregate: {min: requestTime}
    groupBy: [host]
    orderBy: [min_DESC]
  ) 
  {        
    host
    min
  }
}
