query HttpCalculatedMissedData {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"2022-12-18T10:10:10" end:"2022-12-20T10:10:10"}
    }
    groupBy: [ts]
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    missedData
  }
}
