# Equals Operator (field = value)

query GeolocRegionNameEquals {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
      geolocRegionNameEq: "Rio Grande do Sul"
    }
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
