# Greather Than or Equal To Operator (field >= value) 

query StatusGreaterThanOrEqualsTo200 {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
      statusGte: 200
    }
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
