# ILike Operator - Case Insensitive (field ILIKE "value")

query GeolocCountryNameAndRegionNameILike {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
      geolocCountryNameIlike: "braz%"  # Any string that starts with the characters
      geolocRegionNameIlike: "%ao paulo"  # # Any string that ends with the characters.
      schemeIlike: "%HtP%"  # Any string that contains the characters.
    }
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
    scheme
  }
}
