# In Operator (field IN (value1, value2))

query GeolocRegionNameIN {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
      geolocRegionNameIn: ["Rio de Janeiro", "Goias", "Parana"]
    }
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
