# Is Null Operator (field IS NULL) | (field IS NOT NULL)

query GeolocRegionNameIsNotNull {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
      geolocRegionNameIsNull: false
    }
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
