# Like Operator - Case Sensitive (field LIKE "Value")

query GeolocCountryNameAndRegionNameLike {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
      geolocCountryNameLike: "Braz%"  # Any string that starts with the characters
      geolocRegionNameLike: "%ao Paulo"  # # Any string that ends with the characters.
      schemeLike: "%ttp%"  # Any string that contains the characters.
    }
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
    scheme
  }
}
