# Less Than or Equal To Operator (field =< value)

query StatusLessThanOrEqualsTo301 {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
      statusLte: 301
    }
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
