# Less Than or Equal To Operator (field =< value)

query StatusLessThanOrEqualsTo301 {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
      statusLte: 301
    }
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
