# Not Equals Operator (field != value)

query StatusNotEquals429 {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"2023-03-22T17:03:00", end:"2023-03-22T18:05:00"}
      statusNe: 429
    }
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
