# Not Operator (WHERE NOT conditional)

# The two conditions below will be negated: both the status and the geolocCountryName, returning all information 
# that doesn't have a status of 200 and that isn't from Brazil or the United States.

query StatusAndGeolocCountryNameNOT {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
      not: {
        status: 200
        geolocCountryNameIn: ["Brazil", "United States"]
      }
    }
    orderBy: [ts_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
