# Order By ASC - Ascending

query GeolocRegionNameAndCountryNameASC {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    orderBy: [geolocRegionName_ASC, geolocCountryName_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
