# Order By ASC - Ascending

query GeolocRegionNameAndCountryNameASC {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
    }
    orderBy: [geolocRegionName_ASC, geolocCountryName_ASC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
