# Order By DESC - Descending

query GeolocRegionNameAndCountryNameDESC {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"yyyy-mm-ddThh:mm:ss", end:"yyyy-mm-ddThh:mm:ss"}
    }
    orderBy: [geolocRegionName_DESC, geolocCountryName_DESC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
