# Order By DESC - Descending

query GeolocRegionNameAndCountryNameDESC {
  httpMetrics(
    limit: 1000
    filter: {
      tsRange: {begin:"xxxx-xx-xxTxx:xx:xx", end:"xxxx-xx-xxTxx:xx:xx"}
    }
    orderBy: [geolocRegionName_DESC, geolocCountryName_DESC]
  ) 
  {        
    ts
    host
    status
    geolocRegionName
    geolocCountryName
  }
}
