query totalImagesProcessedRequestsPerSecond {
  imagesProcessedMetrics(
    aggregate: {
      rate: requests
    }
    limit: 100
    filter: {
      tsRange: {begin:"2023-03-20T19:52:00", end:"2023-03-20T20:52:00"}
      or: {
          status: 304
          statusRange: { begin: 200, end: 299 }
      }
    }
    groupBy:[ts]
    orderBy:[ts_ASC]
  )
  {
    ts
    rate
  }
}
